---

paths:
  angular: 'angular.min'
  angularRoute: 'angular-route.min'
  angularResource: 'angular-resource.min'
  jquery: 'jquery.min'
  domReady: 'domReady'

shim:
  angular:
    deps: ['jquery']
    exports: 'angular'
  angularRoute:
    deps: ['angular']
  angularResource:
    deps: ['angular']

  jquery:
    deps: []
    exports: 'jquery'
